name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.4"

      - name: Run unit CI
        run: make ci
